### ISSUE TITLE
Herramienta de chequeo de releases

### ISSUE THREAD

**Issue by dlopezp** [gortazar/trabajos-fin-de-grado#1]
Buenas

Mi nombre es Daniel López (@dlopezp_dev) y estaría interesado en este TFG.

Saludos

**Comment by gortazar** [comment]
Daniel, créate un repositorio para el proyecto. Elige un nombre significativo en inglés, como por ejemplo "release-checker", y me añades como colaborador. Luego seguimos hablando ya a través de issues en tu proyecto. 

Cuando esté, contestas a este issue indicando la url del proyecto.

**Comment by dlopezp** [comment]
Hecho

https://github.com/dlopezp/release-checker

**Comment by gortazar** [comment]
@dlopezp no tengo acceso al repositorio. ¿Me has añadido como colaborador?

**Comment by dlopezp** [comment]
Si, te reenvío la invitación

**Comment by dlopezp** [comment]
https://github.com/dlopezp/release-checker/invitations

**Comment by gortazar** [comment]
Ok, ahora sí.

Estoy usando zube.io para la gestión de los proyectos. Se integra muy bien con GitHub. He creado un proyecto en zube.io conectado con tu repositorio para que llevemos ahí la planificación. Date de alta (puedes hacerlo con tu cuenta de GitHub). Verás que te aparece tu proyecto (ya lo he creado yo). Una vez que tengas acceso al proyecto en zube.io, dímelo por aquí y empezamos a planificar cosas.

**Comment by dlopezp** [comment]
Ya estoy dado de alta, pero no veo el proyecto.

Le he dado a enlazar el mío de GH pero creo que lo ha creado de nuevo.

**Comment by gortazar** [comment]
Acabo de crear un issue en zube.io. Mira a ver si lo ves en tu proyecto de zube.io. Aparece también en los issues de GitHub, pero ahora lo que nos interesa es comprobar que nos vemos en zube.io. Debemos poder ver los dos la planificación del proyecto.

**Comment by dlopezp** [comment]
No, en zube no lo veo

**Comment by dlopezp** [comment]
Perdona Patxi, si que lo veo, estaba mirando en Tickets, no en Issues
