### ISSUE TITLE
Plugin de Jenkins para visualizar el estado general del entorno de integración continua

### ISSUE THREAD

**Issue by carlosyaen** [gortazar/trabajos-fin-de-grado#2]
Buenos días,
mi nombre es Carlos Yáñez de 3º año de Ingeniería de Computadores y me interesa este proyecto.
Un saludo

**Comment by gortazar** [comment]
Hola Carlos, créate un repositorio en tu cuenta de GitHub y me añades como colaborador externo.  Ponle un nombre significativo, como "jenkins-infrastructure-monitoring", y copias la url en este issue.

**Comment by carlosyaen** [comment]
Repositorio creado:
https://github.com/carlosyaen/jenkins-infrastructure-monitoring

**Comment by gortazar** [comment]
Ok, acabo de aceptar tu invitación.

Estoy usando zube.io para la gestión de los proyectos. Se integra muy bien con GitHub. He creado un proyecto en zube.io conectado con tu repositorio para que llevemos ahí la planificación. Date de alta (puedes hacerlo con tu cuenta de GitHub). Verás que te aparece tu proyecto (ya lo he creado yo). Deberías ver un issue con el título "Meeting point".

Si tienes problemas coméntamelo por aquí.
