### ISSUE TITLE
Plugin de Jenkins para generar gráficas de rendimiento

### ISSUE THREAD

**Issue by jcfernandezrebollo** [gortazar/trabajos-fin-de-grado#3]
Buenos dias Patxi,
soy Juan Carlos Fernández de 3º de computadores, y estoy interesado en este proyecto.
Un saludo!

**Comment by gortazar** [comment]
Juan Carlos, créate un repositorio en tu cuenta de GitHub y me añades como colaborador externo.  Ponle un nombre significativo, como "jenkins-flame-graphs", y copias la url en este issue cuando lo tengas.

**Comment by jcfernandezrebollo** [comment]
Buenas, aqui esta mi repositorio:
https://github.com/jcfernandezrebollo/jenkins-flame-graphs

**Comment by gortazar** [comment]
Ok, acabo de aceptar tu invitación.

Estoy usando zube.io para la gestión de los proyectos. Se integra muy bien con GitHub. He creado un proyecto en zube.io conectado con tu repositorio para que llevemos ahí la planificación. Date de alta (puedes hacerlo con tu cuenta de GitHub). Verás que te aparece tu proyecto (ya lo he creado yo). Deberías ver un issue con el título "Meeting point".

Si tienes problemas coméntamelo por aquí.
