### ISSUE TITLE
Plugin de Jenkins para visualizar claramente las causas de fallo de los jobs

### ISSUE THREAD

**Issue by mmariscalg** [gortazar/trabajos-fin-de-grado#4]
Buenas Patxi,

Soy Mario, de la semipresencial. Estuvimos hablando sobre los TFGs en la presentación de Sistemas Distribuidos. Me interesa este proyecto. 

Un saludo

**Comment by gortazar** [comment]
Mario, créate un repositorio en tu cuenta de GitHub y añádeme como colaborador externo al proyecto. Ponle un nombre significativo como "jenkins-test-failure-magnifier". Cuando lo hayas hecho pon un comentario a este issue con la url.

**Comment by mmariscalg** [comment]
Creo que ya está: 
https://github.com/mmariscalg/jenkins-test-failure-magnifier

**Comment by gortazar** [comment]
Perfecto. Ya tengo acceso.

Estoy usando zube.io para la gestión de los proyectos. Se integra muy bien con GitHub. He creado un proyecto en zube.io conectado con tu repositorio para que llevemos ahí la planificación. Date de alta (puedes hacerlo con tu cuenta de GitHub). Verás que te aparece tu proyecto (ya lo he creado yo). Deberías ver un issue con el título "Meeting point".

Si tienes problemas coméntamelo por aquí.
