### ISSUE TITLE
Plugin de Jenkins para generar gráficas de rendimiento

### ISSUE THREAD

**Issue by gsalguero** [gortazar/trabajos-fin-de-grado#5]
Buenas Patxi,

Soy Guillermo Salguero de 3º de Informatica Semipresencial, estoy interesado en realizar este TFG.

Saludos.

**Comment by gortazar** [comment]
Ok, Guillermo. Créate un repositorio en GitHub en tu cuenta personal con algún nombre significativo, como "jenkins-performance-plugin", y me añades como colaborador. Luego pon la url del repositorio como comentario en este issue para que yo sepa cuál es. A partir de entonces ya planificamos en tu proyecto.

**Comment by gsalguero** [comment]
Buenas,

Aquí te dejo el link https://github.com/gsalguero/jenkins-performance-plugin.

**Comment by gortazar** [comment]
Ok, acabo de aceptar tu invitación.

Estoy usando zube.io para la gestión de los proyectos. Se integra muy bien con GitHub. He creado un proyecto en zube.io conectado con tu repositorio para que llevemos ahí la planificación. Date de alta (puedes hacerlo con tu cuenta de GitHub). Verás que te aparece tu proyecto (ya lo he creado yo). Deberías ver un issue con el título "Meeting point". 

Si tienes problemas coméntamelo por aquí.
