### ISSUE TITLE
Herramienta de análisis de log

### ISSUE THREAD

**Issue by etrujillog** [gortazar/trabajos-fin-de-grado#6]
Hola Patxi, soy Esteban Trujillo de GIC y estaría interesado en el TFG de Herramienta de análisis de log.

Un saludo.

**Comment by gortazar** [comment]
Hola Esteban, créate un repositorio en tu cuenta de GitHub y me añades como colaborador externo. Ponle un nombre significativo, como "log-analyzer", y copias la url en este issue.

**Comment by etrujillog** [comment]
Aquí esta la url: https://github.com/etrujillog/log-analyzer

**Comment by gortazar** [comment]
Perfecto. Ya tengo acceso.

Estoy usando zube.io para la gestión de los proyectos. Se integra muy bien con GitHub. He creado un proyecto en zube.io conectado con tu repositorio para que llevemos ahí la planificación. Date de alta (puedes hacerlo con tu cuenta de GitHub). Verás que te aparece tu proyecto (ya lo he creado yo). Deberías ver un issue con el título "Meeting point".

Si tienes problemas coméntamelo por aquí.
