### ISSUE TITLE
Plugin de Jenkins para visualizar claramente las causas de fallo de los jobs

### ISSUE THREAD

**Issue by edugithub** [gortazar/trabajos-fin-de-grado#9]
Hola Patxi, 
Soy Eduardo Benito, del Grado de Ingeniería Informática. Me gustaría realizar esta propuesta de TFG.
Un saludo.

**Comment by gortazar** [comment]
Hola Eduardo, créate un repositorio en tu cuenta de GitHub y me añades como colaborador externo. Ponle un nombre significativo, como "jenkins-job-failure-magnifier", y copias la url en este issue.

**Comment by edugithub** [comment]
Vale, esta es la url:
https://github.com/edugithub/jenkins-job-failure-magnifier

**Comment by gortazar** [comment]
Añádeme como colaborador, por favor. Para que pueda darte de alta en la herramienta donde vamos a ir llevando el desarrollo del proyecto.

**Comment by gortazar** [comment]
Ok, acabo de aceptar tu invitación.

Estoy usando zube.io para la gestión de los proyectos. Se integra muy bien con GitHub. He creado un proyecto en zube.io conectado con tu repositorio para que llevemos ahí la planificación. Date de alta (puedes hacerlo con tu cuenta de GitHub). Verás que te aparece tu proyecto (ya lo he creado yo). Deberías ver un issue con el título "Meeting point".

Si tienes problemas coméntamelo por aquí.
